---
title: "Homework 6 - lvr2115"
author: "Laura Robles-Torres"
date: "2023-11-30"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r load packages, message=FALSE}
library(modelr)
library(tidyverse)
library(mgcv)
library(p8105.datasets)

set.seed(1)
```

# Problem 2

```{r import data, message=FALSE}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2022-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(id, USW00094728 = "CentralPark_NY"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

This code creates a multiple linear regression model with 'tmax' as the response with 'tmin' and 'prcp' as the predictors. 

```{r}
fit = lm(tmax ~ tmin + prcp, data = weather_df)

fit |> 
  broom::glance()

fit |>
  broom::tidy()
```

```{r dist of r squared with plot}
#bootstrapping
weather_r2 = 
  weather_df |> 
    modelr::bootstrap(n = 500, id="strap_number") |> 
    mutate(
     models = map(.x=strap, ~lm(tmax ~ tmin + prcp, data = .x)),
     results = map(.x=models, broom::glance)) |> 
    select(strap_number, results) |>
    unnest(results) 

#plot
weather_r2 |> 
  ggplot(aes(x = r.squared)) + geom_density()

#confidence intervals
weather_r2|>
  group_by(strap_number) |> 
  summarize(
    ci_lower = quantile(r.squared, 0.025), 
    ci_upper = quantile(r.squared, 0.975))
```


```{r dist of log of b1*b2 with plot}
#bootstrapping
weather_log =
  weather_df |> 
    modelr::bootstrap(n = 500, id="strap_number") |> 
     mutate(
      models = map(.x=strap, ~lm(tmax ~ tmin + prcp, data = .x)),
      results = map(.x=models, broom::tidy))|>
    select(strap_number, results) |>
    unnest(results) |>
    pivot_wider(
      names_from = term, 
      values_from = estimate) |>
    group_by(strap_number) |>
    summarize(
     log_product=log(tmin*prcp)
    )

#plot
weather_log |>
  ggplot(aes(x=log_product))+geom_density()

#confidence intervals 
weather_log|>
  group_by(strap_number) |> 
  summarize(
    ci_lower = quantile(log_product, 0.025), 
    ci_upper = quantile(log_product, 0.975))
```

